repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.13 # Verifique se essa é a versão mais recente: https://github.com/astral-sh/ruff-pre-commit
    hooks:
      - id: ruff
        args: ["--fix"] # Remove se não quiser aplicar correções automáticas
      - id: ruff-format
