services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U project-avatar"]
      interval: 3s
      timeout: 3s
      retries: 5