from typing import Protocol
from uuid import UUID

from app.models.user_model import UserModel


class UserRepositoryProtocol(Protocol):
    async def get_by_id(self, user_id: UUID) -> UserModel | None: ...
    async def get_by_email(self, email: str) -> UserModel | None: ...
    async def add(self, user: UserModel) -> None: ...
    async def delete(self, user: UserModel) -> None: ...
    async def refresh(self, user: UserModel) -> None: ...
